crds:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    scrapeTimeout: 10s
    evaluationInterval: 60s
    retention: 6h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.158.160.209.82.nip.io
  config:
    route:
      receiver: "null"
      group_by: ["alertname", "env", "service"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - receiver: "stage-pager"
          matchers:
            - env="stage"
            - severity="critical"
        - receiver: "stage-warning"
          matchers:
            - env="stage"
            - severity="warning"
        - receiver: "dev"
          matchers:
            - env="dev"
    receivers:
      - name: "null"
      - name: "dev"
      - name: "stage-warning"
      - name: "stage-pager"
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

grafana:
  adminUser: admin
  adminPassword: admin123
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.158.160.209.82.nip.io
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logging.svc.cluster.local:3100
      isDefault: false
