apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: demo-app
          env:
            - name: ENV
              value: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: demo-dev.platform-gitops.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-app
                port:
                  number: 80
  tls:
    - secretName: demo-dev-tls
      hosts:
        - demo-dev.platform-gitops.ru
