k3s_version: "v1.35.0+k3s1"

k3s_install_script_url: "https://get.k3s.io"
k3s_config_dir: "/etc/rancher/k3s"
k3s_config_path: "/etc/rancher/k3s/config.yaml"
k3s_kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
k3s_kubeconfig_local_path: "{{ playbook_dir }}/kubeconfig"
k3s_api_server: "{{ ansible_host }}"

k3s_write_kubeconfig_mode: "0644"
k3s_disable:
  - traefik
  - servicelb

k3s_manage_namespaces: true
k3s_base_namespaces:
  - argocd
  - ingress-nginx
  - monitoring
  - logging
  - app-dev
  - app-stage
