apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-stage

resources:
  - ../../base

images:
  - name: registry.gitlab.com/timofey-petrov/demo-app
    newTag: "0.1.0"

patchesStrategicMerge:
  - patch.yaml
