apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: stage
    spec:
      containers:
        - name: demo-app
          env:
            - name: ENV
              value: stage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: demo-stage.platform-gitops.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-app
                port:
                  number: 80
  tls:
    - secretName: demo-stage-tls
      hosts:
        - demo-stage.platform-gitops.ru
