apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.49.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/infra/logging/loki-values.yaml
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.54.1
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $values/infra/logging/fluent-bit-values.yaml
    - repoURL: https://github.com/timofey-petrov/platform-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
