---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCGP713u06JnoarzSQ7XbaaxhwHMdZ80ZJg14C4N36iFb7AUjPxGp1FGXEwd+uxcTzRr90azI7cPUYWtPNnxLihdG8wFvWBc6LkNz5xKnWbQ1x1LJhhCLZnlfCzDYx+7K4fR4dbWmbscEvbDlQw1brZQ8BAU+humnZidfWzNhlr5tBnYcRpgHs8+Tx6ldYnX86e7B8zn1qtjaE+HdIlT9wqYZyOnvnblxIP1Mpt+Qk+dOhDyLwWKZACmLrFG0SjW8eu/Kl19a086H2mlrTA7VOqEmKOkzP0+0g9n8zBz1H7lqWSf9Lix5EYFf8PpyxIlbSk1AbHAyEzuxqI6KEzu/RVf7NrP03UoX/3dMsNKqAOr+nCZ8aJEzZMSeA6y7mJ6drKiNHAYbRFRcN2ulALnII0xqDYDn7Ec0DboaZEHZeFc3XEma2rE4O47AiGl4DZ3fu3AgtpCAC8ql6oeJWfePtDpz6l6CO2Im8tfwMgcY0aKJ1YvZ1pgixmBRJ7nD4PfyOBCcR+qXkytIsMjKRLEy1RofSdb7/ASLqmjbXxEqcgo/5uqkojwkUcV3ex19/Q9LQNa1I1N+LnuP0pfApvHPzQG9FdHh1cpQcm5ZynqT0wJRhWbAaT8rqBmRsLT1UusOjSLOQRfnzepFRPc+nTyVdkxiKOUaE/AlFL0Pyirax2e64Zo35Dvb/IeSuQBItxi+daofGqWmXY0VA+V15a9rqOZGZ8aZo=
    admin-user: AgCVWyGRPdxGQEmSIVn0znFiikvyL16KSTdkjEVKRWx4LnXZQmcG0cNZ6mO3pJFAsBxJVL6+vZ3YtEueg8bNXL6WaDVUzFwduWT2PTYltLISKW88vWFlH/tI2FhLktfL4YJi8tdEklIQpVCFx2ioZcAqueiGa4hyzP/OdJzwj0QgbG7KOxsAeBZHkWBUqlOXsYeER/Pm2W389mOMoQHrt7a7mTyetPlLhXMTXNipsjSwPgZMa6PagML1dIDtuQwum0YDEZMqbqQPpOLzD5ADLfop3SmxdBKfzeTg8LAcz/mwOYtGX1t8PotAmLldLK2HrbK+33ZiQYXkZKZVXmgxpYzL3kewEAeuU2QRAlQBXpavEhPWplStzhIc/fYROroNu36NEDuLBTUYASJUsBZR11cvYwaYzNck863Bfnsgm8xvqhtMkkNabC+J5MypAI0BF04O9x0UZCI0gsTIw9ZXsOLMgJ3IWXzpIwMHJ61gpYqI0GSUc9JaeEqjZM3vC2mv7MeM2nsh7gkmLu0MJtLxWlnWGKrJCa+WG8FvxTEBqo1EeicUFa1oc+1DAOKxLwMuAq6VMCiOXwwM9owv8nmRChO201Y9HUZdi81Dwb4XNyp72YDJIUDIUp5Z2OYF7ji5D0BJeax56ZvExAO1vWdVv90Hc0YPW+K0iz887w9aXmo2e9KpjFpQ4hwvcWNIc9e9vIOEg+zd5Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
